server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 172.16.223.3
    port: 6379
  elasticsearch:
    rest:
      uris: http://172.16.223.3:9200
feign:
  sentinel:
    enabled: true

