server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.223.3:3306/guli_pms
    username: root
    password: AwayMagic-123456
  redis:
    host: 172.16.223.3
    port: 6379
feign:
  sentinel:
    enabled: true
jwt:
  pubFilePath: /Users/guowei/IdeaProjects/gmall/rsa/rsa.pub
  cookieName: GMALL-TOKEN

