server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: tx-gmall-group
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.223.3:3306/guli_cart
    username: root
    password: AwayMagic-123456
  redis:
    host: 172.16.223.3
    port: 6379
  task:
    execution:
      thread-name-prefix: cart-
      pool:
        core-size: 100
        max-size: 500
        keep-alive: 60s
        queue-capacity: 5000
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 172.16.223.3
    port: 5672
    virtual-host: /away
    username: away
    password: away
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 4
feign:
  sentinel:
    enabled: true
jwt:
  pubFilePath: /Users/guowei/IdeaProjects/gmall/rsa/rsa.pub
  cookieName: GMALL-TOKEN
  userKey: user-key
  expire: 15552000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto